//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppPIT.ReferenciaPIT {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ciudadano", Namespace="http://schemas.datacontract.org/2004/07/WcfServicio")]
    [System.SerializableAttribute()]
    public partial class Ciudadano : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idciudadanoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string iddepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string iddistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idestadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idprovinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nacionalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numdocumentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tipodocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idciudadano {
            get {
                return this.idciudadanoField;
            }
            set {
                if ((object.ReferenceEquals(this.idciudadanoField, value) != true)) {
                    this.idciudadanoField = value;
                    this.RaisePropertyChanged("idciudadano");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string iddepartamento {
            get {
                return this.iddepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.iddepartamentoField, value) != true)) {
                    this.iddepartamentoField = value;
                    this.RaisePropertyChanged("iddepartamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string iddistrito {
            get {
                return this.iddistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.iddistritoField, value) != true)) {
                    this.iddistritoField = value;
                    this.RaisePropertyChanged("iddistrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idestado {
            get {
                return this.idestadoField;
            }
            set {
                if ((object.ReferenceEquals(this.idestadoField, value) != true)) {
                    this.idestadoField = value;
                    this.RaisePropertyChanged("idestado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idprovincia {
            get {
                return this.idprovinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.idprovinciaField, value) != true)) {
                    this.idprovinciaField = value;
                    this.RaisePropertyChanged("idprovincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.nacionalidadField, value) != true)) {
                    this.nacionalidadField = value;
                    this.RaisePropertyChanged("nacionalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombres {
            get {
                return this.nombresField;
            }
            set {
                if ((object.ReferenceEquals(this.nombresField, value) != true)) {
                    this.nombresField = value;
                    this.RaisePropertyChanged("nombres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numdocumento {
            get {
                return this.numdocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.numdocumentoField, value) != true)) {
                    this.numdocumentoField = value;
                    this.RaisePropertyChanged("numdocumento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tipodocumento {
            get {
                return this.tipodocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.tipodocumentoField, value) != true)) {
                    this.tipodocumentoField = value;
                    this.RaisePropertyChanged("tipodocumento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Users", Namespace="http://schemas.datacontract.org/2004/07/WcfServicio")]
    [System.SerializableAttribute()]
    public partial class Users : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string apellidosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string contraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string direccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string apellidos {
            get {
                return this.apellidosField;
            }
            set {
                if ((object.ReferenceEquals(this.apellidosField, value) != true)) {
                    this.apellidosField = value;
                    this.RaisePropertyChanged("apellidos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.contraseñaField, value) != true)) {
                    this.contraseñaField = value;
                    this.RaisePropertyChanged("contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                if ((object.ReferenceEquals(this.direccionField, value) != true)) {
                    this.direccionField = value;
                    this.RaisePropertyChanged("direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dni {
            get {
                return this.dniField;
            }
            set {
                if ((object.ReferenceEquals(this.dniField, value) != true)) {
                    this.dniField = value;
                    this.RaisePropertyChanged("dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.usuarioField, value) != true)) {
                    this.usuarioField = value;
                    this.RaisePropertyChanged("usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaPIT.IServicioPIT")]
    public interface IServicioPIT {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPIT/Ciudadanos", ReplyAction="http://tempuri.org/IServicioPIT/CiudadanosResponse")]
        WebAppPIT.ReferenciaPIT.Ciudadano[] Ciudadanos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPIT/Ciudadanos", ReplyAction="http://tempuri.org/IServicioPIT/CiudadanosResponse")]
        System.Threading.Tasks.Task<WebAppPIT.ReferenciaPIT.Ciudadano[]> CiudadanosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPIT/AgregarCiudadano", ReplyAction="http://tempuri.org/IServicioPIT/AgregarCiudadanoResponse")]
        string AgregarCiudadano(WebAppPIT.ReferenciaPIT.Ciudadano reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPIT/AgregarCiudadano", ReplyAction="http://tempuri.org/IServicioPIT/AgregarCiudadanoResponse")]
        System.Threading.Tasks.Task<string> AgregarCiudadanoAsync(WebAppPIT.ReferenciaPIT.Ciudadano reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPIT/ActualizarCiudadano", ReplyAction="http://tempuri.org/IServicioPIT/ActualizarCiudadanoResponse")]
        string ActualizarCiudadano(WebAppPIT.ReferenciaPIT.Ciudadano reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPIT/ActualizarCiudadano", ReplyAction="http://tempuri.org/IServicioPIT/ActualizarCiudadanoResponse")]
        System.Threading.Tasks.Task<string> ActualizarCiudadanoAsync(WebAppPIT.ReferenciaPIT.Ciudadano reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPIT/DetalleCiudadano", ReplyAction="http://tempuri.org/IServicioPIT/DetalleCiudadanoResponse")]
        WebAppPIT.ReferenciaPIT.Ciudadano DetalleCiudadano(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPIT/DetalleCiudadano", ReplyAction="http://tempuri.org/IServicioPIT/DetalleCiudadanoResponse")]
        System.Threading.Tasks.Task<WebAppPIT.ReferenciaPIT.Ciudadano> DetalleCiudadanoAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPIT/EliminarCiudadano", ReplyAction="http://tempuri.org/IServicioPIT/EliminarCiudadanoResponse")]
        string EliminarCiudadano(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPIT/EliminarCiudadano", ReplyAction="http://tempuri.org/IServicioPIT/EliminarCiudadanoResponse")]
        System.Threading.Tasks.Task<string> EliminarCiudadanoAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPIT/Users", ReplyAction="http://tempuri.org/IServicioPIT/UsersResponse")]
        WebAppPIT.ReferenciaPIT.Users[] Users();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPIT/Users", ReplyAction="http://tempuri.org/IServicioPIT/UsersResponse")]
        System.Threading.Tasks.Task<WebAppPIT.ReferenciaPIT.Users[]> UsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPIT/AgregarUsers", ReplyAction="http://tempuri.org/IServicioPIT/AgregarUsersResponse")]
        string AgregarUsers(WebAppPIT.ReferenciaPIT.Ciudadano reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPIT/AgregarUsers", ReplyAction="http://tempuri.org/IServicioPIT/AgregarUsersResponse")]
        System.Threading.Tasks.Task<string> AgregarUsersAsync(WebAppPIT.ReferenciaPIT.Ciudadano reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPIT/ActualizarUsers", ReplyAction="http://tempuri.org/IServicioPIT/ActualizarUsersResponse")]
        string ActualizarUsers(WebAppPIT.ReferenciaPIT.Ciudadano reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPIT/ActualizarUsers", ReplyAction="http://tempuri.org/IServicioPIT/ActualizarUsersResponse")]
        System.Threading.Tasks.Task<string> ActualizarUsersAsync(WebAppPIT.ReferenciaPIT.Ciudadano reg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPIT/DetalleUsers", ReplyAction="http://tempuri.org/IServicioPIT/DetalleUsersResponse")]
        WebAppPIT.ReferenciaPIT.Ciudadano DetalleUsers(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPIT/DetalleUsers", ReplyAction="http://tempuri.org/IServicioPIT/DetalleUsersResponse")]
        System.Threading.Tasks.Task<WebAppPIT.ReferenciaPIT.Ciudadano> DetalleUsersAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPIT/EliminarUsers", ReplyAction="http://tempuri.org/IServicioPIT/EliminarUsersResponse")]
        string EliminarUsers(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioPIT/EliminarUsers", ReplyAction="http://tempuri.org/IServicioPIT/EliminarUsersResponse")]
        System.Threading.Tasks.Task<string> EliminarUsersAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioPITChannel : WebAppPIT.ReferenciaPIT.IServicioPIT, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioPITClient : System.ServiceModel.ClientBase<WebAppPIT.ReferenciaPIT.IServicioPIT>, WebAppPIT.ReferenciaPIT.IServicioPIT {
        
        public ServicioPITClient() {
        }
        
        public ServicioPITClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioPITClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPITClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioPITClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebAppPIT.ReferenciaPIT.Ciudadano[] Ciudadanos() {
            return base.Channel.Ciudadanos();
        }
        
        public System.Threading.Tasks.Task<WebAppPIT.ReferenciaPIT.Ciudadano[]> CiudadanosAsync() {
            return base.Channel.CiudadanosAsync();
        }
        
        public string AgregarCiudadano(WebAppPIT.ReferenciaPIT.Ciudadano reg) {
            return base.Channel.AgregarCiudadano(reg);
        }
        
        public System.Threading.Tasks.Task<string> AgregarCiudadanoAsync(WebAppPIT.ReferenciaPIT.Ciudadano reg) {
            return base.Channel.AgregarCiudadanoAsync(reg);
        }
        
        public string ActualizarCiudadano(WebAppPIT.ReferenciaPIT.Ciudadano reg) {
            return base.Channel.ActualizarCiudadano(reg);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarCiudadanoAsync(WebAppPIT.ReferenciaPIT.Ciudadano reg) {
            return base.Channel.ActualizarCiudadanoAsync(reg);
        }
        
        public WebAppPIT.ReferenciaPIT.Ciudadano DetalleCiudadano(string id) {
            return base.Channel.DetalleCiudadano(id);
        }
        
        public System.Threading.Tasks.Task<WebAppPIT.ReferenciaPIT.Ciudadano> DetalleCiudadanoAsync(string id) {
            return base.Channel.DetalleCiudadanoAsync(id);
        }
        
        public string EliminarCiudadano(string id) {
            return base.Channel.EliminarCiudadano(id);
        }
        
        public System.Threading.Tasks.Task<string> EliminarCiudadanoAsync(string id) {
            return base.Channel.EliminarCiudadanoAsync(id);
        }
        
        public WebAppPIT.ReferenciaPIT.Users[] Users() {
            return base.Channel.Users();
        }
        
        public System.Threading.Tasks.Task<WebAppPIT.ReferenciaPIT.Users[]> UsersAsync() {
            return base.Channel.UsersAsync();
        }
        
        public string AgregarUsers(WebAppPIT.ReferenciaPIT.Ciudadano reg) {
            return base.Channel.AgregarUsers(reg);
        }
        
        public System.Threading.Tasks.Task<string> AgregarUsersAsync(WebAppPIT.ReferenciaPIT.Ciudadano reg) {
            return base.Channel.AgregarUsersAsync(reg);
        }
        
        public string ActualizarUsers(WebAppPIT.ReferenciaPIT.Ciudadano reg) {
            return base.Channel.ActualizarUsers(reg);
        }
        
        public System.Threading.Tasks.Task<string> ActualizarUsersAsync(WebAppPIT.ReferenciaPIT.Ciudadano reg) {
            return base.Channel.ActualizarUsersAsync(reg);
        }
        
        public WebAppPIT.ReferenciaPIT.Ciudadano DetalleUsers(string id) {
            return base.Channel.DetalleUsers(id);
        }
        
        public System.Threading.Tasks.Task<WebAppPIT.ReferenciaPIT.Ciudadano> DetalleUsersAsync(string id) {
            return base.Channel.DetalleUsersAsync(id);
        }
        
        public string EliminarUsers(string id) {
            return base.Channel.EliminarUsers(id);
        }
        
        public System.Threading.Tasks.Task<string> EliminarUsersAsync(string id) {
            return base.Channel.EliminarUsersAsync(id);
        }
    }
}
